In [340]:
#从所有人脸集中筛选出含有至少20张图片的人物作为数据集，共有62个人
import os
root=".\lfw\lfw"#根目录
datas_list=[]
image_extensions=('.jpg','.jpeg', '.png', '.gif', '.bmp', '.tiff')
for folder_name in os.listdir(root):
    folder_path = os.path.join(root, folder_name)
    if os.path.isdir(folder_path):
        image_count=0
        for file_name in os.listdir(folder_path):
            file_path = os.path.join(folder_path, file_name)            
            if os.path.isfile(file_path) and file_name.lower().endswith(image_extensions):
                image_count += 1
        if image_count >= 20:
            datas_list.append(folder_name)

print(datas_list)
print(len(datas_list))


<>:3: SyntaxWarning: invalid escape sequence '\l'
<>:3: SyntaxWarning: invalid escape sequence '\l'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_22208\3992367476.py:3: SyntaxWarning: invalid escape sequence '\l'
  root=".\lfw\lfw"#根目录


['Alejandro_Toledo', 'Alvaro_Uribe', 'Amelie_Mauresmo', 'Andre_Agassi', 'Angelina_Jolie', 'Ariel_Sharon', 'Arnold_Schwarzenegger', 'Atal_Bihari_Vajpayee', 'Bill_Clinton', 'Carlos_Menem', 'Colin_Powell', 'David_Beckham', 'Donald_Rumsfeld', 'George_Robertson', 'George_W_Bush', 'Gerhard_Schroeder', 'Gloria_Macapagal_Arroyo', 'Gray_Davis', 'Guillermo_Coria', 'Hamid_Karzai', 'Hans_Blix', 'Hugo_Chavez', 'Igor_Ivanov', 'Jack_Straw', 'Jacques_Chirac', 'Jean_Chretien', 'Jennifer_Aniston', 'Jennifer_Capriati', 'Jennifer_Lopez', 'Jeremy_Greenstock', 'Jiang_Zemin', 'John_Ashcroft', 'John_Negroponte', 'Jose_Maria_Aznar', 'Juan_Carlos_Ferrero', 'Junichiro_Koizumi', 'Kofi_Annan', 'Laura_Bush', 'Lindsay_Davenport', 'Lleyton_Hewitt', 'Luiz_Inacio_Lula_da_Silva', 'Mahmoud_Abbas', 'Megawati_Sukarnoputri', 'Michael_Bloomberg', 'Naomi_Watts', 'Nestor_Kirchner', 'Paul_Bremer', 'Pete_Sampras', 'Recep_Tayyip_Erdogan', 'Ricardo_Lagos', 'Roh_Moo-hyun', 'Rudolph_Giuliani', 'Saddam_Hussein', 'Serena_Williams', 'S

In [341]:
#存储所有图片路径的二维列表
image_paths = []
for diffname in datas_list:
    diffpath = os.path.join(root, diffname)
    if os.path.isdir(diffpath):
        files = os.listdir(diffpath)
        image_files = [os.path.join(diffpath, file) for file in files if file.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.gif'))]
        image_paths.append(image_files)
#每个人都只保留20张图片
import random
data_paths=[]
for lists in image_paths:
    new_lists=random.sample(lists,10)
    data_paths.append(new_lists)
print(data_paths)

[['.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0019.jpg', '.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0009.jpg', '.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0034.jpg', '.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0031.jpg', '.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0010.jpg', '.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0027.jpg', '.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0037.jpg', '.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0006.jpg', '.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0025.jpg', '.\\lfw\\lfw\\Alejandro_Toledo\\Alejandro_Toledo_0007.jpg'], ['.\\lfw\\lfw\\Alvaro_Uribe\\Alvaro_Uribe_0035.jpg', '.\\lfw\\lfw\\Alvaro_Uribe\\Alvaro_Uribe_0017.jpg', '.\\lfw\\lfw\\Alvaro_Uribe\\Alvaro_Uribe_0009.jpg', '.\\lfw\\lfw\\Alvaro_Uribe\\Alvaro_Uribe_0015.jpg', '.\\lfw\\lfw\\Alvaro_Uribe\\Alvaro_Uribe_0003.jpg', '.\\lfw\\lfw\\Alvaro_Uribe\\Alvaro_Uribe_0005.jpg', '.\\lfw\\lfw\\Alvaro_Uribe\\Alvaro_Uribe_0022.jpg', '.\\lfw\\lfw\\Alvaro_Uribe\\Alva

In [342]:
#将图片路径加载成图片得到图片列表datas
import cv2
datas=[]
for paths in data_paths:
    images = []  # 存储当前子列表中的图片对象
    for path in paths:
        img = cv2.imread(path)
        images.append(img)
    datas.append(images) 
print(datas)

[[array([[[  2,   0,   1],
        [  2,   0,   1],
        [  2,   0,   1],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  2,   0,   1],
        [  2,   0,   1],
        [  2,   0,   1],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[210, 213, 198],
        [210, 213, 198],
        [212, 212, 198],
        ...,
        [ 71,  52,  45],
        [ 69,  50,  43],
        [ 69,  50,  43]],

       [[210, 213, 198],
        [210, 213, 198],
        [212, 212, 198],
        ...,
        [ 68,  49,  42],
        [ 66,  47,  40],
        [ 66,  47,  40]],

       [[210, 213, 198],
        [210, 213, 198],
        [212, 212, 198],
        ...,
        [ 68,  49,  42],
        [ 66,  47,  40],
        [ 66,  47,  40

In [343]:
#图片预处理
import numpy as np
datas_vector=[]
for images in datas:
    image_vectors=[]
    for img in images:
        img=cv2.resize(img,(150,150))#统一大小
        img=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)#转化为灰度图
        img=img.flatten()#展平为一维向量
        image_vectors.append(img)
    datas_vector.extend(image_vectors)#按列整合为矩阵
for i in datas_vector:
    print(i)

[ 1  1  1 ... 51 49 47]
[ 1  1  1 ... 21  0  0]
[10 11 13 ... 42 42 43]
[101  98  96 ... 138 133 116]
[182 182 189 ...  28  28  28]
[23 34 35 ... 39 39 40]
[ 0  0  0 ... 19 13  7]
[ 1  0  0 ... 39 45 42]
[ 60  68  73 ... 101 102 104]
[188 189 198 ...  57  57  59]
[208 234 228 ...  81  83  81]
[ 0  0  0 ... 19 20 15]
[19 19 19 ... 17 20 23]
[50 49 47 ... 39 19 20]
[199 199 199 ...  13  15  14]
[ 0  0  0 ... 42 36 37]
[ 0  0  0 ... 19 15 17]
[13 10 16 ... 59 51 53]
[ 0  0  0 ...  3  7 11]
[67 69 68 ... 34  0  0]
[0 0 0 ... 1 1 1]
[ 1  1  0 ... 65 65 63]
[90 94 99 ... 71 72 72]
[  1   1   1 ...  96  97 101]
[141 135 130 ... 139 139 135]
[  0   0   0 ... 128 133 130]
[ 0  0  0 ... 47 47 47]
[  0   0   0 ... 159  43  20]
[  0   0   0 ... 195 150  80]
[  0   0   0 ... 139 132 134]
[172 170 166 ... 232 227 223]
[ 90  91  94 ... 112 113 112]
[  0   0   0 ...  69 132 161]
[187 185 186 ...   0   0   0]
[ 0  0  0 ... 74 77 81]
[106 113 116 ...  35  43  38]
[  0   0   0 ... 219 218 218]
[  0   0  

In [344]:
#转化为numpy数组便于矩阵运算
X=np.array(datas_vector)
Y=np.array(datas_list)
print(X)
print(X.shape)

[[ 1  1  1 ... 51 49 47]
 [ 1  1  1 ... 21  0  0]
 [10 11 13 ... 42 42 43]
 ...
 [ 0  0  0 ... 78 80 81]
 [ 1  0  0 ...  0  0  0]
 [ 1  1  0 ... 34 30 31]]
(620, 22500)


In [345]:
#建立图像数据与标签的索引关系
X_index=np.array([])
for i in range(0,X.shape[0]):
    X_index=np.append(X_index,i//10)
print(X_index)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  5.  5.  5.  5.
  5.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  7.  7.
  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.
  9.  9.  9.  9.  9.  9.  9.  9.  9.  9. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12.
 12. 12. 12. 12. 13. 13. 13. 13. 13. 13. 13. 13. 13. 13. 14. 14. 14. 14.
 14. 14. 14. 14. 14. 14. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17.
 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 19. 19. 19. 19. 19. 19. 19. 19.
 19. 19. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 21. 21. 21. 21. 21. 21.
 21. 21. 21. 21. 22. 22. 22. 22. 22. 22. 22. 22. 22. 22. 23. 23. 23. 23.
 23. 23. 23. 23. 23. 23. 24. 24. 24. 24. 24. 24. 24

In [346]:
#划分训练集与测试集
X_column=[range(0,620)]
X_train_index=[]
for i in range(0,62):
    X_part=np.array(range(10*i,10*i+10))
    X_train_part=np.random.choice(X_part,size=7,replace=False,p=None)#随机数取0.7的数据作为训练集
    X_train_index.extend(X_train_part)
X_train_index.sort()
X_test_index=np.setdiff1d(X_column,X_train_index)#余下的0.3数据即为测试集
X_train_index=np.setdiff1d(X_column,X_test_index)
print(X_train_index)#训练集的索引
print(X_test_index)#测试集的索引

[  2   3   4   5   6   7   9  10  12  13  14  16  18  19  20  21  24  25
  27  28  29  30  31  32  33  35  36  37  40  42  44  45  46  47  48  50
  51  54  55  56  57  59  60  63  64  66  67  68  69  71  72  73  74  75
  76  77  80  81  82  84  86  87  88  90  92  94  95  96  98  99 100 102
 103 104 105 107 109 110 111 112 113 115 118 119 120 122 123 124 125 127
 129 132 133 134 135 136 138 139 141 142 143 145 146 147 148 150 151 152
 153 154 155 159 161 162 163 164 166 167 168 171 173 174 175 176 177 178
 180 181 183 185 186 188 189 190 192 193 195 196 198 199 201 202 204 205
 207 208 209 212 213 214 215 216 218 219 220 221 223 225 226 228 229 230
 232 233 235 236 238 239 240 241 242 244 245 247 249 250 251 252 253 255
 257 259 260 262 264 266 267 268 269 270 272 274 275 276 278 279 281 282
 283 284 285 287 288 290 291 292 295 296 297 299 301 302 304 306 307 308
 309 310 311 312 313 315 316 318 321 322 323 324 325 326 329 330 331 334
 335 337 338 339 340 342 344 345 347 348 349 350 35

In [347]:
#根据索引划分出训练集和测试集
#这样测试时可以根据其列序号得到对应的标签序号
X_train=X[X_train_index,:]
X_test=X[X_test_index,:]
print(X_train)
print(X_test)

[[ 10  11  13 ...  42  42  43]
 [101  98  96 ... 138 133 116]
 [182 182 189 ...  28  28  28]
 ...
 [  0   0   0 ...  78  80  81]
 [  1   0   0 ...   0   0   0]
 [  1   1   0 ...  34  30  31]]
[[  1   1   1 ...  51  49  47]
 [  1   1   1 ...  21   0   0]
 [ 60  68  73 ... 101 102 104]
 ...
 [  0   0   0 ...  31  26  24]
 [  1   1   1 ... 140 175 182]
 [  1   1   1 ...  50  48  50]]


In [348]:
#计算平均脸向量
meanFace=np.mean(X_train,axis=0)
print(meanFace)
meanFace_2=meanFace.reshape((150,150))
meanFace_3=Image.fromarray(meanFace_2.astype('uint8'), 'L')
meanFace_3.show()

[52.26036866 53.19354839 53.46774194 ... 73.57373272 73.09447005
 72.11981567]


In [349]:
#将每个图片的一维向量都减去平均向量，得到差值矩阵
X_diff=X_train-meanFace
print(X_diff)
print(X_diff.shape)
print(np.mean(X_diff,axis=0))
#减掉平均脸后的人长这个样子
a=X_diff[0].flatten()
a=a.reshape((150,150))
b=Image.fromarray(a.astype('uint8'), 'L')
b.show()

[[-42.26036866 -42.19354839 -40.46774194 ... -31.57373272 -31.09447005
  -29.11981567]
 [ 48.73963134  44.80645161  42.53225806 ...  64.42626728  59.90552995
   43.88018433]
 [129.73963134 128.80645161 135.53225806 ... -45.57373272 -45.09447005
  -44.11981567]
 ...
 [-52.26036866 -53.19354839 -53.46774194 ...   4.42626728   6.90552995
    8.88018433]
 [-51.26036866 -53.19354839 -53.46774194 ... -73.57373272 -73.09447005
  -72.11981567]
 [-51.26036866 -52.19354839 -53.46774194 ... -39.57373272 -43.09447005
  -41.11981567]]
(434, 22500)
[ 2.78323191e-15 -1.90242087e-14 -2.09560991e-14 ...  2.09560991e-15
 -9.16829336e-15 -2.13490260e-14]


In [350]:
#求差值矩阵的协方差矩阵
X_cov=np.cov(X_diff)#求协方差矩阵
print(X_cov.shape)
#求协方差矩阵的特征值和特征向量
featvalue,featvector=np.linalg.eig(X_cov)
print(featvector.shape)
#得到了特征的排序，取前400个最有影响的特征
feature=featvector[:,0:40]

(434, 434)
(434, 434)


In [351]:
print(feature.shape)
X_feature=np.dot(X_diff.T,feature)
for i in range(0,40):
    X_feature[:,i]=X_feature[:,i]/np.linalg.norm(X_feature[:,i])
X_final=np.dot(X_diff,X_feature)
print(X_final)
#得到样本差值矩阵在特征空间上的投影

(434, 40)
[[-3697.93166226 -2807.60750257  -938.06919486 ...   390.79491744
    783.55709566  -579.22503917]
 [ 2883.09317877  -180.81568719  2365.59368507 ...  -805.95456888
   -459.61474383   815.52653361]
 [-2761.90241533 -4148.38950162  -835.00129671 ...   201.524679
   -168.77041244  -392.34237004]
 ...
 [-2471.72667134 -1832.20230275 -4260.04751793 ...  -306.78854477
     70.8805764    -63.52562415]
 [ -644.75117778 -5576.46124591 -2308.59082619 ...   606.02276353
    238.00855096  -977.14813036]
 [  214.14119807 -4446.34375811  -319.58625306 ...  -251.34109783
    749.88682538  -143.04733691]]


In [352]:
#对测试集处理
X_test=X_test-meanFace
X_test=np.dot(X_test,X_feature)
print(X_test)

[[ 1983.62861231  4798.18186697  -205.0611226  ...  -613.30151784
   -760.46716276  -729.64218897]
 [ 1425.16604521  2717.72683121   379.76721104 ...   674.66080615
   1233.05489717    -5.12762354]
 [-1645.77029198   249.33737361   839.28384929 ...   925.99651468
   -304.04075738   375.37024978]
 ...
 [-3952.61561194 -2925.98215007 -3142.65516993 ...  1791.29609871
    453.71005549  -940.02533122]
 [-3370.48721186  -336.30048144 -2577.6045182  ...  -549.56415395
    295.74780053  -873.55235446]
 [-2865.53027815  -630.43586393 -1116.53088506 ...   712.12451885
   -145.19714681   -80.06555265]]


In [354]:
count=0
for i in range(0,186):
    testface=X_test[i,:]
    diff=X_final-testface
    sqdiff=diff ** 2
    sqDistances = sqdiff.sum(axis=1)
    sortedDistIndicies = sqDistances.argsort()
    min=sortedDistIndicies[0]
    if datas_list[int(X_index[X_train_index[min]])]==datas_list[int(X_index[X_test_index[i]])]:
        print (datas_list[int(X_index[X_train_index[min]])])


Atal_Bihari_Vajpayee
David_Beckham
Gerhard_Schroeder
Hamid_Karzai
Jennifer_Aniston
Jennifer_Aniston
Jiang_Zemin
Juan_Carlos_Ferrero
Tom_Daschle


In [259]:
#测试过程
def Test(sample):
    #得出的特征空间的投影与训练集中每个向量求欧氏距离
    distances=np.array([])
    for i in range(0,868):
        distance=np.linalg.norm(X_feature[i]-sample)
        distances=np.append(distances,distance)
    min=np.argmin(distances)
    column=X_train_index[min]
    result=int(X_index[column])
    return datas_list[result]

In [260]:
count=0
X_test=X_test-np.mean(X_test,axis=0)
X_test_feat=np.dot(X_test,feature)
for i in range(0,372):
    a=Test(X_test_feat[i])
    b=
    if a==b:
        count+=1
print(count/372)

SyntaxError: invalid syntax (2664891222.py, line 6)